spring.application.name=Example
server.port =8082
jdbc:sqlserver://localhost:61522;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=ArticleBase; 
spring.datasource.username=article
spring.datasource.password=pass
